version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  web1:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_ID: SERVER-1
    depends_on:
      - db

  web2:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_ID: SERVER-2
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2

volumes:
  postgres_data: