name: Terraform Apply

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to Repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      
    - name: Terraform Format Check
      working-directory: ./tf
      run: terraform fmt -check || true
  
    - name: Initialize Terraform
      working-directory: ./tf
      run: terraform init

    - name: Validate Terraform
      working-directory: ./tf
      run: terraform validate

    - name: Plan Terraform
      working-directory: ./tf
      run: terraform plan
        
    - name: Apply Terraform
      working-directory: ./tf
      run: terraform apply -auto-approve
